### ISSUE TITLE
所以这里只能搜番号和种子，不能在线观看吧？

### ISSUE THREAD

**Issue by FFFang** [Ccixyj/JBusDriver#10]
有想做下去的想法，先问下在线观看是否不可能实现？

**Comment by Ccixyj** [comment]
对的.在线播放可以使用 简易磁力+mxplayer来实现.
在线播放得获取旋风离线的资源链接

**Comment by cc1024** [comment]
旋风倒闭了，是不是这个方法已经失效了？

**Comment by Ccixyj** [comment]
@cc1024  神奇磁力还是可以的.

javbus 上线了在线视频功能.已经加入1.1.0里程碑.
官网说明如下

> JavBus 視頻服務全球華人用戶
如果您一時無法訪問網站, 請不要著急, 也許服務器上出現了技術故障, 很快就會自動恢復. 
JavBus 視頻永久地址：www.JavBus.pw
非會員每天免費瀏覽30部視頻。
註冊會員每天免費瀏覽50部視頻。
贊助會員無限瀏覽高清視頻。

**Comment by weiyideai520** [comment]
所以，我还是想问下，能在线看吗？

**Comment by Ccixyj** [comment]
@weiyideai520现在版本不行。如果有能力，可以帮我实现个

**Comment by ghkfsk** [comment]
_操_逼_视频,你懂的 [点击进入1](https://www.scc5.top/?111)
         
_操_逼_视频,你懂的 [点击进入2](https://www.scc8.top/?111)
                    
惭凶谰财肆搅湍颖诓惶擅邢泄卜圃

**Comment by hfdetrjs** [comment]
看男女做爱视频,你懂的  [点击进入](https://www.scc5.top/)

看男女做爱视频,你懂的  [点击进入](https://www.scc8.top/)

      
甭子实鼻妒直
