### ISSUE TITLE
还更新吗

### ISSUE THREAD

**Issue by 7peanuts** [Ccixyj/JBusDriver#124]
app里提示有新版本，而且比这里的要高，但是下载跳转到gitee，那的下载地址却又指向这里

**Comment by speeed001** [comment]
> 大佬，app现在还能用吗？我这两天看都是打开后一片空白

app里的gitee不知道为啥访问不了了，我用mt修改了下
https://shishiyu.lanzouh.com/iH58r055si4b

**Comment by M1sato** [comment]
> 
大佬 我重下了你这个链接以后插件没有了 怎么装啊

**Comment by M1sato** [comment]
> 

大佬 我下了你的链接以后之前的插件没有了 怎么再装啊

**Comment by Ccixyj** [comment]
v1.3.3
