### ISSUE TITLE
磁力失效

### ISSUE THREAD

**Issue by baize257** [Ccixyj/JBusDriver#133]

**Comment by Ccixyj** [comment]
抽屉菜单 点击重试，更新插件版本1.1.1就行

**Comment by shadyking111** [comment]
> 抽屉菜单 点击重试，更新插件版本1.1.1就行
怎么更新插件啊，在哪里看这个

**Comment by Ccixyj** [comment]
> > 抽屉菜单 点击重试，更新插件版本1.1.1就行
> > 怎么更新插件啊，在哪里看这个

重新下载1.3.4吧 1.3.3有问题
