### ISSUE TITLE
不知道怎么打开种子连接

### ISSUE THREAD

**Issue by lrroy** [Ccixyj/JBusDriver#16]
不会是复制里头的番号，然后再去别的软件搜索吧？求添加番号磁链接，或者种子收索，像JAViewer那种比较方便。
还有就是ui 优化一下，主题绿色的太伤眼了。
收藏夹能不能来个女友分类，自己添加个文件夹哪种归类。

**Comment by Ccixyj** [comment]
@lrroy 
1.可以优化
2.绿色刺眼吗？可能那个金色刺眼。
3.可以考虑

**Comment by lrroy** [comment]
颜色配个，奶稍黄，米色比较舒服一些，我不知道这个颜色怎么描述。

**Comment by Ccixyj** [comment]
已加入 查看 v1.1.1
