### ISSUE TITLE
放个论坛接口和微信支付宝我想支持一下

### ISSUE THREAD

**Issue by lrroy** [Ccixyj/JBusDriver#38]
如果的话，加入论坛的页面。感觉这样难度有点高。
还有就是，当个微信或者支付宝二维码，想聊表敬意。

**Comment by Ccixyj** [comment]
@lrroy
 这个需求最好是可以通过javbus的接口来做.否则会比较复杂.
如果你有什么好的想法告诉我,或者在telegram群里说. 
支持的话,谢谢啦.我会加入支持开发的.

**Comment by 1357209470** [comment]
@Ccixyj
谢谢大大的软件，收藏分类超赞的
