### ISSUE TITLE
选择磁力链接的时候没有显示是含字幕/非字幕的

### ISSUE THREAD

**Issue by ttsonico** [Ccixyj/JBusDriver#40]
PC端用网页浏览的时候，如果某部片存在字幕版本，磁力链接旁边也会显示“（字幕）”，这个功能可以添加进手机端吗？

**Comment by Ccixyj** [comment]
这个需要磁力链接网站支持.
javbus的磁力链接无法直接抓取,所以无法直接获取是否有字幕.如果抓取javbus的话,当前会有两次访问,这个就不能忍了.

**Comment by Ccixyj** [comment]
参阅 #7.
