### ISSUE TITLE
关于同类软件jav图书馆收藏内容迁移的求助

### ISSUE THREAD

**Issue by fsy953643268** [Ccixyj/JBusDriver#47]
把图书馆软件的json文件（链接: https://pan.baidu.com/s/11ARXAaWwpy7a_0RKSd6r7w 密码: whn3）拖入到备份目录下显示没法恢复，不知道是否有迁移的办法，东西比较多，手动一个一个添加太麻烦～拜托作者了

**Comment by Ccixyj** [comment]
emmm..你其实可以学一下json 和 python 或者 js。有时间帮你转一下

**Comment by Ccixyj** [comment]
@fsy953643268  
取附件解压
[backup.zip](https://github.com/Ccixyj/JBusDriver/files/2219954/backup.zip)
，放入sd卡 `\me.jbusdriver\collect\backup\`下，恢复备份即可

**Comment by fsy953643268** [comment]
非常感谢您
