### ISSUE TITLE
点“收藏夹”-“演员”会闪退

### ISSUE THREAD

**Issue by gogo008** [Ccixyj/JBusDriver#49]
点“收藏夹”-“演员”会闪退

**Comment by Ccixyj** [comment]
1. 确认一下有么有sd卡读写的权限
2. 数据备份下，然后把 `sd/me.jbusdriver/collect/` 下的 `collect.db` 和 `collect.db-journal ` 删除后进入试试。没问题再还原备份
3.  提供下手机型号和版本信息

**Comment by gogo008** [comment]
@Ccixyj 如你所料，我是用的是整个文件夹直接覆盖sd卡根目录的备份方式。经您提醒，现在解决了。谢谢

**Comment by gogo008** [comment]
按照您的方法试了，还是会闪退“程序停止运行”点击“电影“和”链接“没问题，唯独点”演员“会出现如上问题…
设备：samaung n920c，android7.0，已root

2018年8月3日星期五，Maxium_R <notifications@github.com> 写道：
