### ISSUE TITLE
添加磁力链接(待定)

### ISSUE THREAD

**Issue by Ccixyj** [Ccixyj/JBusDriver#5]

**Comment by CooperWen** [comment]
可以分享个二维码让我一表心意吗.

**Comment by Ccixyj** [comment]
@CooperWen 尽情使用吧。

_Sent from my HUAWEI NXT-DL00 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lw960105** [comment]
什么时间添加磁力功能  复制出来搜很麻烦 256Lux系列没有

**Comment by hnuzhoulin** [comment]
自带磁链搜索+1

**Comment by 1sunnylight** [comment]
我怎么找不到下载的地方啊，求指教。。。

**Comment by Ccixyj** [comment]
查看v1.1.1
