### ISSUE TITLE
加载出问题点击重试，老是同一个链接

### ISSUE THREAD

**Issue by younghang** [Ccixyj/JBusDriver#63]
老哥这个软件用了一年了，感觉很好用，表示感谢！但最近点击重试老是加载同一个链接，这样就一直加载不出来，这版之前的点击重试就会自己换个链接加载。
版本1.2.15build477

**Comment by Ccixyj** [comment]
可用的话是会随机到同一个的。你多试几次

**Comment by Ccixyj** [comment]
嗯，知道了，你可以先用老版本
