### ISSUE TITLE
克隆代码打开项目时遇到的一个错误。

### ISSUE THREAD

**Issue by Neoqee** [Ccixyj/JBusDriver#77]
ERROR: Could not get unknown property 'GradleVersion' for project ':app' of type org.gradle.api.Project.
这个错误提示的GradleVersion怎么解决？

 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by Ccixyj** [comment]
参考issue#76

**Comment by Ccixyj** [comment]
或者调低gradle wrapper 的版本
