### ISSUE TITLE
为什么搜索女优搜索不到？还有公司也是

### ISSUE THREAD

**Issue by JamesHarden13913** [Ccixyj/JBusDriver#85]
![Screenshot_20190813_000242_me jbusdriver](https://user-images.githubusercontent.com/54035523/62879465-c1a5fd80-bd5d-11e9-94a7-187affc53c74.jpg)

**Comment by Ccixyj** [comment]
姿势不正确。搜一下 上原亜衣

**Comment by JamesHarden13913** [comment]
那为什么搜欧美的女优也搜不出来？

**Comment by JamesHarden13913** [comment]
> 姿势不正确。搜一下 上原亜衣

那为什么搜欧美的女优也搜不出来？
