### ISSUE TITLE
ERROR: Cannot get property 'variantData' on null object

### ISSUE THREAD

**Issue by vanishcode** [Ccixyj/JBusDriver#89]
![TIM图片20191105094158](https://user-images.githubusercontent.com/20496444/68171904-8f98e600-ffb0-11e9-9121-f67933970366.png)

基于最新代码
Android Studio 3.5.2
Build #AI-191.8026.42.35.5977832, built on October 31, 2019
JRE: 1.8.0_202-release-1483-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by vanishcode** [comment]
已解决。

**Comment by suzuoshen** [comment]
?怎么解决的？
